name: Build Level Hash

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabi
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Setup Rust
      run: |
       curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s  -- -y && \
       rustup install nightly && \
       rustup default nightly && \
       rustup target add ${{ matrix.target }}
    - name: Build
      run: cargo build --target ${{ matrix.target }}
    - name: Run tests
      if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
      run: cargo test
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: |
          target/${{ matrix.target }}/liblevel_hash.so
